- name: varisble from inventory
  hosts: local
  connection: local
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "I am learning {{ COURSE }}, duration is {{ DURATION }}, from the trainer is {{ TRAINER }}"


#ansible-playbook -i inventory.ini 11.vars.argument.yaml -e "COURSE=ARGS" -e "DURATION=10MINS" -e "TRAINER=lokesh"